export const AppRoutes = {
    MAIN: "/",
    Andrian:"/Andrian/*",
    Ihor: '/ihor/*',
    NOT_FOUND: "/404",
    MENTOR: "/mentor/*",
    HOC: "/hoc",
    CV: "/cv",
    NATALIA: "/natalia/*",
    Solomiya: '/solomiya/*',
    Iryna:"/Iryna/*",
    Vitalii:"/Vitalii/*",
    Sasha: "/sasha/*",
    NataliaKoziar:"/NataliaKoziar/*",
    Andrew: '/andrew/*',
    FORM: "/form",
    BTN: "/NataComp",
    INPUT:"/NataInputComp",
    CONSULT: "/consult",
    AXIOS: "/axios",
    newAxios:"/newAxios",
    StepanRudiak: "/StepanRudiak/*",
    REDUX: "/redux",
    MainComponent:"/liftState",
    InputState:"/inputState",
    FormState:"/formState",
}

export const RedirectRoutes = {
    MAIN: "/",
    Andrian:"/Andrian/",
    Ihor: '/ihor',
    NOT_FOUND: "/404",
    MENTOR: "/mentor",
    HOC: "/hoc",
    Solomiya: '/solomiya',
    Vitalii: '/vitalii',
    Sasha: "/sasha",
    Iryna:"/Iryna",
    CV:"/cv",
    NATALIA:"/natalia",
    NataliaKoziar:"/NataliaKoziar",
    Andrew:'/andrew',
    newAxios:"/newAxios",
    News:"News",
    Applause:"Applause",
    MainComponent:"/liftState",
    InputState:"/inputState",
    FormState:"/formState",
    StepanRudiak: "/StepanRudiak",
    mentor_users: "/mentor/users",
}

